mounts:
  - local: foo/client
    remote: foo/server
    once:
      - mode: sync
        path: blah.txt
    watch:
      - mode: sync
        path: .
        exclude:
          - exclude-me.txt